AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM template with Lambda, API Gateway & GitHub actions pre-configured
Parameters:
  EnvType:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: Must specify "dev" (default), "test" or "prod"
Conditions:
  IsProd: !Equals [!Ref EnvType, prod]
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: nodejs16.x
    Tracing: Active
    AutoPublishAlias: !Ref EnvType
    Architectures:
      - arm64
Resources:
  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler.handler
      CodeUri: ../example-service
      Description: SAM template demo
  ExampleFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: ExampleFunction
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub /${AWS::Partition}/lambda/${ExampleFunction}
      RetentionInDays: 14
Outputs:
  ExampleFunctionArn:
    Value: !GetAtt ExampleFunction.Arn
  ExampleFunctionLogGroup:
    Value: !Ref ExampleFunctionLogGroup