version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dev-<%= name %>-service"
s3_prefix = "dev-<%= name %>-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-b214ddbb"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"

[test]
[test.deploy]
[test.deploy.parameters]
stack_name = "test-<%= name %>-service"
s3_prefix = "test-<%= name %>-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-b214ddbb"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvType=test"

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "prod-<%= name %>-service"
s3_prefix = "prod-<%= name %>-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-b214ddbb"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvType=prod"