AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template demo
Parameters:
  EnvType:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: nodejs16.x
    Tracing: Active
    AutoPublishAlias: !Ref EnvType
    Architectures:
      - arm64
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension-Arm64:2
    Environment:
      Variables:
        TABLE_NAME: '{{resolve:secretsmanager:user-service/prod:SecretString:TABLE_NAME}}'
        LAMBDA_INSIGHTS_LOG_LEVEL: info
Resources:
  RestApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref EnvType
      TracingEnabled: true
      MethodSettings:
      - HttpMethod: '*'
        LoggingLevel: INFO
        ResourcePath: '/*'
        MetricsEnabled: true
        DataTraceEnabled: true
  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler/get-user-handler.handler
      CodeUri: ../user-service
      Description: SAM template demo
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - CloudWatchLambdaInsightsExecutionRolePolicy
        - AWSXRayDaemonWriteAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref RestApiGateway
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false
        EntryPoints: 
          - src/handler/get-user-handler.ts
  AddUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler/add-user-handler.handler
      CodeUri: ../user-service
      Description: SAM template demo
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - CloudWatchLambdaInsightsExecutionRolePolicy
        - AWSXRayDaemonWriteAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId: !Ref RestApiGateway
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false
        EntryPoints: 
          - src/handler/add-user-handler.ts
  GetUserFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: GetUserFunction
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub /${AWS::Partition}/lambda/${GetUserFunction}
      RetentionInDays: 14
  AddUserFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: AddUserFunction
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub /${AWS::Partition}/lambda/${AddUserFunction}
      RetentionInDays: 14
Outputs:
  ApiEndpointUrl:
    Value: !Sub https://${RestApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${EnvType}/
  GetUserFunctionArn:
    Value: !GetAtt GetUserFunction.Arn
  GetUserFunctionLogGroup:
    Value: !Ref GetUserFunctionLogGroup
  AddUserFunctionArn:
    Value: !GetAtt AddUserFunction.Arn
  AddUserFunctionLogGroup:
    Value: !Ref AddUserFunctionLogGroup