AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM template with Lambda, API Gateway & GitHub actions pre-configured
Parameters:
  EnvType:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: Must specify "dev" (default), "test" or "prod"
Conditions:
  IsProd: !Equals [!Ref EnvType, prod]
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: nodejs16.x
    Tracing: Active
    AutoPublishAlias: !Ref EnvType
    Architectures:
      - arm64
Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler.handler
      CodeUri: ../test-service
      Description: SAM template demo
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false
        EntryPoints: 
          - src/handler.ts
  TestFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: TestFunction
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub /${AWS::Partition}/lambda/${TestFunction}
      RetentionInDays: 14
Outputs:
  TestFunctionArn:
    Value: !GetAtt TestFunction.Arn
  TestFunctionLogGroup:
    Value: !Ref TestFunctionLogGroup