name: Deploy Dev
on:
  push:
    branches:
      - dev

env:
  SAM_CLI_TELEMETRY: 0

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 2
    outputs:
      run-timestamp: ${{ steps.run-timestamp.outputs.timestamp }}

    steps:
      - name: Pull the full git history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate a timestamp for this run
        id: run-timestamp
        run: echo ::set-output name=timestamp::$(date +'%s%N')
        shell: bash

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true

      - name: Install node modules
        run: npm ci

      - name: Run code analysis
        run: npm run affected:lint -- --base=refs/remotes/origin/dev~1 --head=refs/remotes/origin/dev

  test:
    name: Test
    needs: 
      - lint
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Pull the full git history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true

      - name: Install node modules
        run: npm ci

      - name: Run tests
        run: npm run affected:test -- --base=refs/remotes/origin/dev~1 --head=refs/remotes/origin/dev

  build:
    name: Build
    needs: 
      - lint
      - test
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Pull the full git history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true

      - name: Install node modules
        run: npm ci

      - name: Install AWS SAM
        uses: aws-actions/setup-sam@v1

      - name: Build Lambda artifacts
        shell: bash
        run: npm run affected:build -- --base=refs/remotes/origin/dev~1 --head=refs/remotes/origin/dev --args='--EnvType=dev'

      - name: Cache the build directory
        uses: actions/cache@v2
        with:
          path: ./.aws-sam/*
          key: ${{ github.sha }}-build-${{ needs.config.outputs.run-timestamp }}

  deploy:
    name: Deploy
    needs: 
      - lint
      - test
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Pull the full git history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Install AWS SAM
        uses: aws-actions/setup-sam@v1

      - name: Restore the build directory from cache
        uses: actions/cache@v2
        with:
          path: ./.aws-sam/*
          key: ${{ github.sha }}-build-${{ needs.config.outputs.run-timestamp }}

      - name: Deploy the build artifacts
        shell: bash
        run: npm run affected:deploy -- --base=refs/remotes/origin/dev~1 --head=refs/remotes/origin/dev --args='--EnvType=dev'
